

FREQUENCIES VARIABLES=uf Região Porte_pop2010 q36_3 q36_4 q36_5 q36_6 q36_7 D36_8 d36_4
  /ORDER=ANALYSIS.

* Export Output.

* Export Output.
OUTPUT EXPORT
  /CONTENTS  EXPORT=ALL  LAYERS=PRINTSETTING  MODELVIEWS=PRINTSETTING
  /XLS  DOCUMENTFILE='D:\Enviar\Tabelas_Acolhimento_RH.xls'
     OPERATION=CREATEFILE
     LOCATION=LASTCOLUMN  NOTESCAPTIONS=YES.
