* Encoding: UTF-8.
*** RENAME LABELS CREAS DADOS GERAIS - 2016

VARIABLE LABELS
IBGE6   =   'IBGE6'
NU_identificador   =  'NU_identificador'
ident1	'ident1_Nome que identifica o CREAS:'
ident2	'ident2_Selecione/Indique o Tipo de Logradouro (avenida, rua, etc):'
ident3	'ident3_Endereço:'
ident4	'ident4_Número:'
ident5	'ident5_Complemento:'
ident6	'ident6_Bairro:'
ident7	'ident7_Ponto de Referência:'
ident8	'ident8_CEP:'
ident9	'ident9_Município:'
ident10	'ident10_UF:'
ident11	'ident11_E-mail:'
ident12	'ident12_DDD - Telefone:'
ident13	'ident13_Ramal:'
ident14	'ident14_Fax:'
ident15	'ident15_Data de Implantação do CREAS:'
q1	'q1_Localização:'
q2	'q2_Tipo de CREAS:'
q2.3	'q2.3_Em caso de deslocamento das famílias/indivíduos para a sede deste CREAS Regional, existe apoio para este deslocamento?'
q3.1	'q3.1_Horário de funcionamento - Dias por semana:'
q3.2	'q3.2_Horário de funcionamento - Horas por dia:'
q4	'q4_Situação do imóvel onde se localiza o CREAS:'
q5	'q5_O imóvel de funcionamento deste CREAS é compartilhado?'
q6.1	'q6.1_1 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Secretaria da Assistência Social ou congênere'
q6.2	'q6.2_2 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel:  Outra unidade administrativa (Sede de Prefeitura, Administração Regional, Sub-Prefeitura, etc.)'
q6.3	'q6.3_3 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Conselho Municipal de Assistência Social'
q6.4	'q6.4_4 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: CRAS  Centro de Referência de Assistência Social'
q6.5	'q6.5_5 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Centro POP - Centro de Referência Especializado para População em Situação de Rua'
q6.6	'q6.6_6 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Unidade de Acolhimento institucional (Abrigo)'
q6.7	'q6.7_7 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Outra unidade pública de serviços da Assistência Social'
q6.8	'q6.8_8 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Unidade de Saúde'
q6.9	'q6.9_9 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Centro de Referência de Atendimento à Mulher (CRAM)'
q6.10	'q6.10_10 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: ONG/Entidade/ Associação Comunitária'
q6.11	'q6.11_11 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Conselho Tutelar'
q6.12	'q6.12_12 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Delegacia Especializada'
q6.13	'q6.13_13 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Outro órgão de defesa de direitos (Ministério Público, Defensoria Pública, Poder Judiciário, etc.)'
q6.14	'q6.14_14 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: NAI - Núcleo de Atendimento Integrado'
q6.99	'q6.99_99 Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel: Outros'
q6.99.1	'q6.99.1_Especifique o tipo de unidade com a qual este CREAS compartilha o imóvel - Qual?'
q7.1	'q7.1_1 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Apenas o endereço é o mesmo, mas todos os espaços do CREAS são independentes e de uso exclusivo, inclusive a entrada'
q7.2	'q7.2_2 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Entrada / Porta de Acesso'
q7.3	'q7.3_3 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Recepção'
q7.4	'q7.4_4 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Algumas salas de atendimento individualizado'
q7.5	'q7.5_5 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Todas as salas de atendimento individualizado'
q7.6	'q7.6_6 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Algumas salas de atendimento coletivo'
q7.7	'q7.7_7 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Todas as salas de atendimento coletivo'
q7.8	'q7.8_8 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Salas administrativas'
q7.9	'q7.9_9 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Banheiros'
q7.10	'q7.10_10 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Copa/cozinha'
q7.11	'q7.11_11 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Área Externa'
q7.12	'q7.12_12 Especifique quais espaços do imóvel são compartilhados entre o CREAS e a(s) outra (s) Unidade (s): Almoxarifado ou similar'
q8.1	'q8.1_Descreva o espaço físico deste CREAS: Quantidade de salas com capacidade máxima para 5 pessoas'
q8.2	'q8.2_Descreva o espaço físico deste CREAS: Quantidade de salas com capacidade para 6 a 14 pessoas'
q8.3	'q8.3_Descreva o espaço físico deste CREAS: Quantidade de salas com capacidade para 15 a 29 pessoas'
q8.4	'q8.4_Descreva o espaço físico deste CREAS: Quantidade de salas com capacidade para 30 ou mais pessoas'
q8.5	'q8.5_Descreva o espaço físico deste CREAS: Salas específicas para uso da Coordenação, equipe técnica ou administração (Não são salas de atendimento!)'
q8.6	'q8.6_Descreva o espaço físico deste CREAS: Quantidade total de banheiros'
q8.7	'q8.7_Descreva o espaço físico deste CREAS: Possui Recepção?'
q8.8	'q8.8_Descreva o espaço físico deste CREAS: Possui Cozinha/Copa?'
q8.9	'q8.9_Descreva o espaço físico deste CREAS: Possui Almoxarifado ou similar?'
q8.10	'q8.10_Descreva o espaço físico deste CREAS: Possui Espaço externo no CREAS para atividades de convívio?'
q9.1	'q9.1_Assinale as condições de acessibilidade para pessoas com mobilidade reduzida que este CREAS possui: Acesso principal adaptado com rampas e rota acessível desde a calçada até a recepção do CREAS'
q9.2	'q9.2_Assinale as condições de acessibilidade para pessoas com mobilidade reduzida que este CREAS possui: Rota acessível aos principais espaços do CREAS (recepção, sala(s) de atendimento e sala(s) de uso coletivo)'
q9.3	'q9.3_Assinale as condições de acessibilidade para pessoas com mobilidade reduzida que este CREAS possui: Rota acessível ao banheiro'
q9.4	'q9.4_Assinale as condições de acessibilidade para pessoas com mobilidade reduzida que este CREAS possui: Banheiro adaptado para pessoas com mobilidade reduzida (idosos, pessoas com deficiência, etc.)'
q10.1	'q10.1_1Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Telefone'
q10.2	'q10.2_2 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Impressora'
q10.3	'q10.3_3 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Televisão (TV)'
q10.4	'q10.4_4 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Equipamento de som'
q10.5	'q10.5_5 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: DVD/Blu-Ray/Vídeo Cassete'
q10.6	'q10.6_6 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Datashow'
q10.7	'q10.7_7 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Câmera Fotográfica'
q10.8	'q10.8_8 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Filmadora'
q10.9	'q10.9_9 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Veículo de uso exclusivo'
q10.10	'q10.10_10 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Veículo de uso compartilhado'
q10.11	'q10.11_11 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Acervo bibliográfico'
q10.12	'q10.12_12 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Mobiliário/materiais para atender crianças (mesa infantil, tapete emborrachado, brinquedos, etc.)'
q10.13	'q10.13_13 Indique os equipamentos e materiais disponíveis, em perfeito funcionamento, para o desenvolvimento dos serviços deste CREAS: Materiais pedagógicos, culturais e esportivos'
q11	'q11_Quantidade total de computadores no CREAS'
q12	'q12_Quantos estão conectados à internet no CREAS'
q13	'q13_Este CREAS possui placa de identificação?'
q14.1.1	'q14.1.1_ Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência física 1 Crianças e adolescentes'
q14.1.2	'q14.1.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência física 2 Mulheres adultas'
q14.1.3	'q14.1.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência física 3 Homens adultos'
q14.1.4	'q14.1.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência física 4 Idosos'
q14.1.5	'q14.1.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência física 5 Não atende este tipo de situação'
q14.2.1	'q14.2.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência psicológica 1 Crianças e adolescentes'
q14.2.2	'q14.2.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência psicológica 2 Mulheres adultas'
q14.2.3	'q14.2.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência psicológica 3 Homens adultos'
q14.2.4	'q14.2.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência psicológica 4 Idosos'
q14.2.5	'q14.2.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Violência psicológica 5 Não atende este tipo de situação'
q14.3.1	'q14.3.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Abuso sexual/Violência Sexual -1 Crianças e adolescentes '
q14.3.2	'q14.3.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Abuso sexual/Violência Sexual - 2 Mulheres adultas'
q14.3.3	'q14.3.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Abuso sexual/Violência Sexual - 3 Homens adultos'
q14.3.4	'q14.3.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Abuso sexual/Violência Sexual - 4 idosos'
q14.3.5	'q14.3.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Abuso sexual/Violência Sexual - 5 Não atende este tipo de situação'
q14.4.1	'q14.4.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Exploração sexual -1 Crianças e adolescentes '
q14.4.2	'q14.4.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Exploração sexual - 2 Mulheres adultas'
q14.4.3	'q14.4.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Exploração sexual - 3 Homens adultos'
q14.4.4	'q14.4.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Exploração sexual - 4 idosos'
q14.4.5	'q14.4.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Exploração sexual - 5 Não atende este tipo de situação'
q14.5.1	'q14.5.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Negligência e abandono -1 Crianças e adolescentes '
q14.5.4	'q14.5.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Negligência e abandono - 4 idosos'
q14.5.5	'q14.5.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Negligência e abandono - 5 Não atende este tipo de situação'
q14.6.1	'q14.6.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Tráfico de pessoas -1 Crianças e adolescentes '
q14.6.2	'q14.6.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Tráfico de pessoas - 2 Mulheres adultas'
q14.6.3	'q14.6.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Tráfico de pessoas - 3 Homens adultos'
q14.6.4	'q14.6.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Tráfico de pessoas - 4 idosos'
q14.6.5	'q14.6.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Tráfico de pessoas - 5 Não atende este tipo de situação'
q14.7.1	'q14.7.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Trabalho infantil - 1 Crianças e adolescentes'
q14.7.5	'q14.7.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Trabalho infantil - 5 Não atende este tipo de situação'
q14.8.1	'q14.8.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Situação de rua -1 Crianças e adolescentes '
q14.8.2	'q14.8.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Situação de rua - 2 Mulheres adultas'
q14.8.3	'q14.8.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Situação de rua - 3 Homens adultos'
q14.8.4	'q14.8.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Situação de rua - 4 idosos'
q14.8.5	'q14.8.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Situação de rua - 5 Não atende este tipo de situação'
q14.9.1	'q14.9.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência da orientação sexual - 1 Crianças e adolescentes'
q14.9.2	'q14.9.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência da orientação sexual - 2 Mulheres adultas'
q14.9.3	'q14.9.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência da orientação sexual - 3 Homens adultos '
q14.9.4	'q14.9.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência da orientação sexual - 4 idosos'
q14.9.5	'q14.9.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência da orientação sexual - 5 Não atende este tipo de situação'
q14.10.1	'q14.10.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência de raça/etnia - 1 Crianças e adolescentes'
q14.10.2	'q14.10.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência de raça/etnia - 2 Mulheres adultas'
q14.10.3	'q14.10.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência de raça/etnia - 3 Homens adultos'
q14.10.4	'q14.10.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência de raça/etnia - 4 idosos'
q14.10.5	'q14.10.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Discriminação em decorrência de raça/etnia - 5 Não atende este tipo de situação'
q14.11.1	'q14.11.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Pessoas com deficiência vítimas de violência/violação de direitos - 1 Crianças e adolescentes '
q14.11.2	'q14.11.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Pessoas com deficiência vítimas de violência/violação de direitos - 2 Mulheres adultas'
q14.11.3	'q14.11.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Pessoas com deficiência vítimas de violência/violação de direitos - 3 Homens adultos'
q14.11.4	'q14.11.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Pessoas com deficiência vítimas de violência/violação de direitos - 4 idosos'
q14.11.5	'q14.11.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Pessoas com deficiência vítimas de violência/violação de direitos - 5 Não atende este tipo de situação'
q14.12.1	'q14.12.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Família/Indivíduos com pessoas em serviços de acolhimento - 1 Crianças e adolescentes '
q14.12.2	'q14.12.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Família/Indivíduos com pessoas em serviços de acolhimento - 2 Mulheres adultas'
q14.12.3	'q14.12.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Família/Indivíduos com pessoas em serviços de acolhimento - 3 Homens adultos'
q14.12.4	'q14.12.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Família/Indivíduos com pessoas em serviços de acolhimento - 4 idosos'
q14.12.5	'q14.12.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Família/Indivíduos com pessoas em serviços de acolhimento - 5 Não atende este tipo de situação'
q14.13.1	'q14.13.1_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com adolescentes em cumprimento de Medida Socioeducativa - 1 Crianças e adolescentes'
q14.13.5	'q14.13.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com adolescentes em cumprimento de Medida Socioeducativa - 5 Não atende este tipo de situação'
q14.14.2	'q14.14.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas adultas em privação de liberdade - 2 Mulheres Adultas '
q14.14.3	'q14.14.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas adultas em privação de liberdade - 3 Homens Adultos'
q14.14.4	'q14.14.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas adultas em privação de liberdade - 4 Idosos'
q14.14.5	'q14.14.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas adultas em privação de liberdade - 5 Não atende este tipo de situação'
q14.15.2	'q14.15.2_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas egressas do sistema prisional - 2 Mulheres Adultas'
q14.15.3	'q14.15.3_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas egressas do sistema prisional - 3 Homens Adultos'
q14.15.4	'q14.15.4_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas egressas do sistema prisional - 4 Idosos'
q14.15.5	'q14.15.5_Indique se o CREAS oferta atendimento, pelo PAEFI, para as seguintes situações e ciclos de vida: Famílias com pessoas egressas do sistema prisional - 5 Não atente este tipo de situação'
q15.1	'q15.1_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 1 Acolhida Particularizada realizada por técnico de nível superior'
q15.2	'q15.2_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 2 Acompanhamento individual/familiar'
q15.3	'q15.3_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 3 Acompanhamento dos encaminhamentos realizados'
q15.4	'q15.4_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 4 Registro do acompanhamento individual/familiar em prontuário'
q15.5	'q15.5_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 5 Elaboração do Plano de Acompanhamento Familiar'
q15.6	'q15.6_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 6 Elaboração de relatórios técnicos sobre casos em acompanhamento'
q15.7	'q15.7_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 7 Grupo/oficina com famílias ou indivíduos'
q15.8	'q15.8_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 8 Orientação jurídico-social'
q15.9	'q15.9_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 9 Visitas domiciliares'
q15.10	'q15.10_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 10 Palestras'
q15.11	'q15.11_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 11 Ações de mobilização e sensibilização para o enfrentamento das situações de violação de direitos'
q15.12	'q15.12_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 12 Apoio para obtenção de documentação pessoal'
q15.13	'q15.13_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 13 Orientação/acompanhamento para inserção no BPC'
q15.14	'q15.14_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 14 Encaminhamento para o CRAS'
q15.15	'q15.15_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 15 Encaminhamento de famílias ou indivíduos para a rede de serviço socioassistencial'
q15.16	'q15.16_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 16 Encaminhamento para serviços da rede de saúde'
q15.17	'q15.17_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 17 Encaminhamento de famílias ou indivíduos para outras políticas públicas (educação, habitação, trabalho, etc.)'
q15.18	'q15.18_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 18 Encaminhamento para o Conselho Tutelar'
q15.19	'q15.19_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 19 Encaminhamento para órgãos de defesa e responsabilização (Defensoria Pública, Promotoria, Ministério Público, etc.)'
q15.20	'q15.20_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 20 Encaminhamento para obtenção de Benefícios Eventuais'
q15.21	'q15.21_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 21 Encaminhamento para inserção/atualização de famílias no Cadastro Único'
q15.99	'q15.99_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI 99 Outros'
q15.99.1	'q15.99.1_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do PAEFI Quais?'
q16.1	'q16.1_A.1. Total de casos (famílias ou indivíduos) em acompanhamento pelo PAEFI'
q17.1	'q17.1_Quantos casos são referentes a famílias residentes no município sede de CREAS?'
q17.2	'q17.2_Quantos casos são referentes a famílias residentes em outros municípios?'
q18.1.1	'q18.1.1_Autores de agressão intrafamiliar - 1 Oficinas com ações preventivas'
q18.1.2	'q18.1.2_Autores de agressão intrafamiliar - 2 Apoio à reinserção social'
q18.1.99	'q18.1.99_Autores de agressão intrafamiliar - 99 Outras atividades de atendimento / acompanhamento'
q18.1.0	'q18.1.0_Autores de agressão intrafamiliar - 0 Não realiza atendimento ou acompanhamento'
q18.2.1	'q18.2.1_Egressos do sistema prisional - 1 Oficinas com ações preventivas '
q18.2.2	'q18.2.2_Egressos do sistema prisional - 2 Apoio à reinserção social'
q18.2.99 	'q18.2.99 _Egressos do sistema prisional - 99 Outras atividades de atendimento / acompanhamento'
q18.2.0 	'q18.2.0 _Egressos do sistema prisional - 0 Não realiza atendimento ou acompanhamento'
q18.3.1	'q18.3.1_Famílias com pessoas em situação de violação de direito em decorrência do uso de álcool e outras drogas - 1 Oficinas com ações preventivas'
q18.3.2	'q18.3.2_Famílias com pessoas em situação de violação de direito em decorrência do uso de álcool e outras drogas - 2 Apoio a reinserção social'
q18.3.3	'q18.3.3_Famílias com pessoas em situação de violação de direito em decorrência do uso de álcool e outras drogas - 3 Encaminhamento monitorado para a rede de saúde '
q18.3.99	'q18.3.99_Famílias com pessoas em situação de violação de direito em decorrência do uso de álcool e outras drogas - 99 Outras atividades de atendimento / acompanhamento'
q18.3.0	'q18.3.0_Famílias com pessoas em situação de violação de direito em decorrência do uso de álcool e outras drogas - 0 Não realiza atendimento ou acompanhamento'
q19.1	'q19.1_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 1 Pessoa com Deficiência'
q19.2	'q19.2_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 2 Questões de Gênero'
q19.3	'q19.3_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 3 População em situação de rua'
q19.4	'q19.4_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 4 População LGBT'
q19.5	'q19.5_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 5 Povos e comunidades tradicionais (indígenas, quilombolas, ribeirinhos, extrativistas, dentre outros)'
q19.6	'q19.6_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 6 Álcool e outras drogas'
q19.7	'q19.7_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 7 Cor, Raça e etnia'
q19.8	'q19.8_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 8 Violências e violações de direitos'
q19.9	'q19.9_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 9 Sistema Socioeducativo - SINASE (inclusive MSE)'
q19.10	'q19.10_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 10 Pessoa Idosa'
q19.11	'q19.11_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 11 Tráfico de Seres Humanos'
q19.12	'q19.12_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 12 Trabalho Infantil'
q19.99	'q19.99_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 99 Outros'
q19.0	'q19.0_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? 0 Não participou de capacitação'
q19.99.1	'q19.99.1_Nesta Unidade há profissionais que já participaram de capacitação sobre os seguinte(s) tema(s)? Especifique:'
q20	'q20_Este CREAS realiza o Serviço de Proteção Social a Adolescentes em Cumprimento de Medida Socioeducativa de Liberdade Assistida (LA) e de Prestação de Serviços à Comunidade (PSC)'
q21	'q21_Informe o total de adolescentes em cumprimento de Medidas Socioeducativas (LA e/ou PSC)'
q22	'q22_Desse total, de quantos adolescentes há informações sobre o ato infracional que gerou a medida?'
q22.1	'q22.1_Quantidade de adolescentes sobre os quais não há informações sobre o ato infracional'
q23.1.1	'q23.1.1_Furto - 12 e 13 anos'
q23.1.2	'q23.1.2_Furto - 14 e 15 anos'
q23.1.3	'q23.1.3_Furto - 16 e 17 anos'
q23.1.4	'q23.1.4_Furto - 18 a 21 anos'
q23.1.5	'q23.1.5_Furto - Total'
q23.2.1	'q23.2.1_Roubo - 12 e 13 anos'
q23.2.2	'q23.2.2_Roubo - 14 e 15 anos'
q23.2.3	'q23.2.3_Roubo - 16 e 17 anos'
q23.2.4	'q23.2.4_Roubo - 18 a 21 anos'
q23.2.5	'q23.2.5_Roubo - Total'
q23.3.1	'q23.3.1_Tráfico - 12 e 13 anos'
q23.3.2	'q23.3.2_Tráfico - 14 e 15 anos'
q23.3.3	'q23.3.3_Tráfico - 16 e 17 anos'
q23.3.4	'q23.3.4_Tráfico - 18 a 21 anos'
q23.3.5	'q23.3.5_Tráfico - Total'
q23.4.1	'q23.4.1_Agressão/Briga - 12 e 13 anos'
q23.4.2	'q23.4.2_Agressão/Briga - 14 e 15 anos'
q23.4.3	'q23.4.3_Agressão/Briga - 16 e 17 anos'
q23.4.4	'q23.4.4_Agressão/Briga - 18 a 21 anos'
q23.4.5	'q23.4.5_Agressão/Briga - Total'
q23.5.1	'q23.5.1_Homicídio - 12 e 13 anos'
q23.5.2	'q23.5.2_Homicídio - 14 e 15 anos'
q23.5.3	'q23.5.3_Homicídio - 16 e 17 anos'
q23.5.4	'q23.5.4_Homicídio - 18 a 21 anos'
q23.5.5	'q23.5.5_Homicídio - Total'
q23.6.1	'q23.6.1_Tentativa de Homicídio - 12 e 13 anos'
q23.6.2	'q23.6.2_Tentativa de Homicídio - 14 e 15 anos'
q23.6.3	'q23.6.3_Tentativa de Homicídio - 16 e 17 anos'
q23.6.4	'q23.6.4_Tentativa de Homicídio - 18 a 21 anos'
q23.6.5	'q23.6.5_Tentativa de Homicídio - Total'
q23.7.1	'q23.7.1_Dano ao Patrimônio - 12 e 13 anos'
q23.7.2	'q23.7.2_Dano ao Patrimônio - 14 e 15 anos'
q23.7.3	'q23.7.3_Dano ao Patrimônio - 16 e 17 anos'
q23.7.4	'q23.7.4_Dano ao Patrimônio - 18 a 21 anos'
q23.7.5	'q23.7.5_Dano ao Patrimônio - Total'
q23.8.1	'q23.8.1_Crime de trânsito/dirigir sem habilitação - 12 e 13 anos'
q23.8.2	'q23.8.2_Crime de trânsito/dirigir sem habilitação - 14 e 15 anos'
q23.8.3	'q23.8.3_Crime de trânsito/dirigir sem habilitação - 16 e 17 anos'
q23.8.4	'q23.8.4_Crime de trânsito/dirigir sem habilitação - 18 a 21 anos'
q23.8.5	'q23.8.5_Crime de trânsito/dirigir sem habilitação - Total'
q23.9.1	'q23.9.1_Porte/uso de drogas - 12 e 13 anos'
q23.9.2	'q23.9.2_Porte/uso de drogas - 14 e 15 anos'
q23.9.3	'q23.9.3_Porte/uso de drogas - 16 e 17 anos'
q23.9.4	'q23.9.4_Porte/uso de drogas - 18 a 21 anos'
q23.9.5	'q23.9.5_Porte/uso de drogas - Total'
q23.10.1	'q23.10.1_Lesão Corporal - 12 e 13 anos'
q23.10.2	'q23.10.2_Lesão Corporal - 14 e 15 anos'
q23.10.3	'q23.10.3_Lesão Corporal - 16 e 17 anos'
q23.10.4	'q23.10.4_Lesão Corporal - 18 a 21 anos'
q23.10.5	'q23.10.5_Lesão Corporal - Total'
q23.11.1	'q23.11.1_Outros - 12 e 13 anos'
q23.11.2	'q23.11.2_Outros - 14 e 15 anos'
q23.11.3	'q23.11.3_Outros - 16 e 17 anos'
q23.11.4	'q23.11.4_Outros - 18 a 21 anos'
q23.11.5	'q23.11.5_Outros - Total'
q23.12.1	'q23.12.1_Total - 12 e 13 anos'
q23.12.2	'q23.12.2_Total - 14 e 15 anos'
q23.12.3	'q23.12.3_Total - 16 e 17 anos'
q23.12.4	'q23.12.4_Total - 18 a 21 anos'
q23.12.5	'q23.12.5_Total - Total'
q23.99.1	'q23.99.1_Qual(is) outro(s) ato(s) infacional(is)?'
q24.1 	'q24.1 _Liberdade Assistida'
q24.1.1	'q24.1.1_Liberdade Assistida - Não Sabe'
q24.2	'q24.2_Prestação de Serviços à Comunidade'
q24.2.1 	'q24.2.1 _Prestação de Serviços à Comunidade - Não Sabe'
q25	'q25_O Serviço de Proteção Social a Adolescentes em Cumprimento de Medida Socioeducativa de Liberdade Assistida (LA) e de Prestação de Serviços à Comunidade (PSC) está inscrito no Conselho Municipal dos Direitos da Criança e Adolescente (CMDCA)?'
q26	'q26_A equipe técnica responsável pelo Serviço de Proteção Social a Adolescentes em Cumprimento de Medida Socioeducativa (MSE) de Liberdade Assistida (LA) e de Prestação de Serviços à Comunidade (PSC) é exclusiva deste serviço?'
q27	'q27_Indique abaixo a frequência com que, normalmente, cada adolescente em cumprimento de medida socioeducativa de Liberdade Assistida (LA) é atendido neste CREAS'
q28.1	'q28.1_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 1 Elaboração do Plano Individual de Atendimento (PIA) do adolescente'
q28.2	'q28.2_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 2 Atendimento individual do adolescente'
q28.3	'q28.3_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 3 Atendimento do adolescente em grupos'
q28.4	'q28.4_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 4 Atendimento da família do adolescente em cumprimento de medida de Liberdade Assistida (LA)'
q28.5	'q28.5_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 5 Atendimento com grupos de famílias do adolescente em cumprimento de medida de Liberdade Assistida (LA)'
q28.6	'q28.6_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 6 Visita domiciliar'
q28.7	'q28.7_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 7 Encaminhamento do adolescente para o sistema educacional'
q28.8	'q28.8_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 8 Acompanhamento da frequência escolar do adolescente'
q28.9	'q28.9_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 9 Encaminhamento para os Serviços de Convivência e Fortalecimento de Vínculos'
q28.10	'q28.10_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 10 Encaminhamento do adolescente e sua família para outros serviços e programas da rede socioassistencial'
q28.11	'q28.11_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 11 Encaminhamento para serviços da rede de saúde para atendimento de usuários/dependentes de substâncias psicoativas'
q28.12	'q28.12_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 12 Encaminhamento de famílias ou indivíduos para outros serviços da rede de saúde'
q28.13	'q28.13_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 13 Encaminhamento do adolescente e sua família para serviços de outras políticas setoriais'
q28.14	'q28.14_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 14 Encaminhamento do adolescente para cursos profissionalizantes'
q28.15	'q28.15_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 15 Elaboração e encaminhamento de relatório para a Justiça da Infância e da Juventude ou Ministério Público'
q28.16	'q28.16_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 16 Elaboração e encaminhamento de relatórios periódicos para o órgão gestor da assistência social no município'
q28.17	'q28.17_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 17 Registro do acompanhamento em prontuário'
q28.18	'q28.18_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 18 Encaminhamento da família e/ou adolescente ao PAEFI'
q28.19	'q28.19_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito da Liberdade Assistida (LA) - 19 Discussão de caso com outros profissionais da rede'
q29	'q29_Indique abaixo a frequência com que, normalmente, cada adolescente em cumprimento de medida socioeducativa de Prestação de Serviço de Comunidade (PSC) é atendido neste CREAS'
q30.1	'q30.1_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 1 Rede de Saúde'
q30.2	'q30.2_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 2 Rede Educacional'
q30.3	'q30.3_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 3 Rede socioassistencial pública'
q30.4	'q30.4_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 4 Rede socioassistencial privada (ONGs/entidade/associação comunitária)'
q30.5	'q30.5_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 5 Outras Unidades da administração pública (Ex.: Corpo de Bombeiros, sede da administração municipal, etc.)'
q30.99	'q30.99_Indique os principais locais onde o adolescente presta serviço à comunidade nesta localidade: - 99 Outros'
q30.99.1	'q30.99.1_Qual(is)?'
q31.1	'q31.1_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 1 Elaboração do Plano Individual de Atendimento (PIA) do adolescente'
q31.2	'q31.2_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 2 Encaminhamento do adolescente para os locais de prestação de serviços comunitários'
q31.3	'q31.3_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 3 Atendimento individual do adolescente'
q31.4	'q31.4_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 4 Atendimento do adolescente em grupos'
q31.5	'q31.5_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 5 Atendimento da família do adolescente em cumprimento de medida de Prestação de Serviços à Comunidade (PSC)'
q31.6	'q31.6_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do (PSC) - 6 Atendimento com grupos de famílias do adolescente em cumprimento de medida de Prestação de Serviço à Comunidade'
q31.7	'q31.7_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 7 Visita domiciliar'
q31.8	'q31.8_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 8 Visitas técnicas aos locais de prestação do serviço à comunidade'
q31.9	'q31.9_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 9 Encaminhamento do adolescente para o sistema educacional'
q31.10	'q31.10_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 10 Encaminhamento da família e/ou do adolescente ao PAEFI'
q31.11	'q31.11_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 11 Discussão de caso com outros profissionais da rede'
q31.12	'q31.12_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 12 Acompanhamento da freqüência escolar do adolescente'
q31.13	'q31.13_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 13 Encaminhamento para o Serviço de Convivência e Fortalecimento de Vínculos'
q31.14	'q31.14_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 14 Encaminhamento do adolescente e sua família para outros serviços e programas da rede socioassistencial'
q31.15	'q31.15_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do  (PSC) - 15 Encaminhamento para serviços da rede de saúde para atendimento de usuários/dependentes de substâncias psicoativas'
q31.16	'q31.16_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 16 Encaminhamento de famílias ou indivíduos para outros serviços da rede de saúde'
q31.17	'q31.17_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 17 Encaminhamento do adolescente e sua família para serviços de outras políticas setoriais'
q31.18	'q31.18_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 18 Encaminhamento do adolescente para cursos profissionalizantes'
q31.19	'q31.19_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do Prestação de Serviço à Comunidade (PSC) - 19 Elaboração e encaminhamento de relatório para a Justiça da Infância e da Juventude ou Ministério Público'
q31.20	'q31.20_Indique as ações e atividades realizadas pelos profissionais deste CREAS no âmbito do (PSC) - 20 Elaboração e encaminhamento de relatórios periódicos para o órgão gestor da assistência social no município'
q32	'q32_Este CREAS realiza o Serviço Especializado em Abordagem Social?'
q33.1	'q33.1_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 1 Identificação de situações de risco pessoal e social com direitos violados'
q33.2	'q33.2_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 2 Conhecimento do Território'
q33.3	'q33.3_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 3 Informação, comunicação e defesa de direitos'
q33.4	'q33.4_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 4 Escuta e orientação'
q33.5	'q33.5_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 5 Encaminhamentos sobre/para a rede de serviços locais'
q33.6	'q33.6_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 6 Articulação da rede de serviços socioassistenciais'
q33.7	'q33.7_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 7 Articulação com os serviços de políticas públicas setoriais'
q33.8	'q33.8_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? - 8 Articulação interinstitucional com os demais órgãos do Sistema de Garantia de Direitos'
q33.9	'q33.9_Quais as atividades realizadas pelo Serviço Especializado em Abordagem Social? -  9 Elaboração de relatórios'
q34.1	'q34.1_Como são definidas as áreas onde serão realizadas as abordagens do Serviço Especializado em Abordagem Social? - 1 Conhecimento prévio dos técnicos do Serviço'
q34.2	'q34.2_Como são definidas as áreas onde serão realizadas as abordagens do Serviço Especializado em Abordagem Social? - 2 A partir de diagnósticos socioterritoriais realizados pelo órgão gestor de Assistência Social'
q34.3	'q34.3_Como são definidas as áreas onde serão realizadas as abordagens do Serviço Especializado em Abordagem Social? - 3 Demanda dos órgãos de defesa de direitos'
q34.4	'q34.4_Como são definidas as áreas onde serão realizadas as abordagens do Serviço Especializado em Abordagem Social? - 4 Denúncias/Solicitações da população'
q34.99	'q34.99_Como são definidas as áreas onde serão realizadas as abordagens do Serviço Especializado em Abordagem Social? - 99 Outros'
q34.99.1	'q34.99.1_Qual?'
q35	'q35_Quantos dias por semana a abordagem social é realizada:'
q36	'q36_Em quais períodos do dia costuma ser realizada a abordagem social:'
q37.0	'q37.0_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 0 Não possui Serviço realizado por unidade referenciada'
q37.1	'q37.1_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 1 Cumpre função de coordenador do Serviço referenciado'
q37.2	'q37.2_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 2 Coleta/recebe periodicamente informações sobre dados de atendimento do Serviço'
q37.3	'q37.3_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 3 Realiza reuniões periódicas para avaliação do Serviço com a unidade referenciada'
q37.4	'q37.4_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 4 Participa do processo de planejamento das atividades do Serviço'
q37.5	'q37.5_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 5 Acompanha cotidianamente as atividades do Serviço'
q37.6	'q37.6_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 6 Constrói estratégias metodológicas do Serviço'
q37.7	'q37.7_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 7 Elabora relatórios técnicos específicos sobre casos atendidos/acompanhados pelo Serviço'
q37.8	'q37.8_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 8 Realiza estudos de caso em parceria com o Serviço'
q37.9	'q37.9_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 9 Define procedimentos comuns e/ou complementares ao Serviço'
q37.10	'q37.10_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 10 Possui fluxos de encaminhamentos e trocas de informações com o Serviço'
q37.11	'q37.11_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 11 Articula com a rede de serviços socioassistenciais'
q37.12	'q37.12_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 12 Articula com a rede dos serviços das políticas públicas setoriais'
q37.13	'q37.13_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 13 Articula com os demais órgãos do Sistema de Garantia de Direitos'
q37.99	'q37.99_No caso da execução do Serviço de Abordagem por unidade referenciada, indique as atividades realizadas por este CREAS: - 99 Não realiza nenhuma das atividades acima'
q38	'q38_Esta Unidade oferta o Serviço de Proteção Social Especial para Pessoas com Deficiência, Idosas e suas Famílias'
q39	'q39_O Serviço de Proteção Social Especial para Pessoas com Deficiência, Idosas e suas Famílias é executado:'
q40	'q40_O Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias, ofertado nesta Unidade, possui capacidade para atender quantos usuários por turno'
q41	'q41_Em média, quantos dias por semana os usuários frequentam este serviço'
q42	'q42_Em média, quantas horas por dia os usuários do Serviço permanecem na Unidade (nos dias em que este utiliza o serviço)?'
q43.1	'q43.1_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 1 Acolhida e escuta inicial'
q43.2	'q43.2_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 2 Estudo social'
q43.3	'q43.3_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 3 Orientação sobre acesso ao BPC e outros benefícios'
q43.4	'q43.4_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 4 Orientação e apoio para obtenção de documentação pessoal'
q43.5	'q43.5_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 5 Orientação para realização de cadastro no CadÚnico'
q43.6	'q43.6_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 6 Elaboração de Plano de Acompanhamento Individual e/ou Familiar'
q43.7	'q43.7_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 7 Oficinas e atividades coletivas de convívio e socialização'
q43.8	'q43.8_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 8 Encaminhamento para a rede de serviços socioassistenciais'
q43.9	'q43.9_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 9 Encaminhamento para os serviços da rede de saúde'
q43.10	'q43.10_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 10 Encaminhamento para política de educação'
q43.11	'q43.11_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 11 Encaminhamento para serviços/Unidades das demais políticas públicas'
q43.12	'q43.12_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 12 Encaminhamento para órgãos de defesa de direitos)'
q43.13	'q43.13_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 13 Acompanhamento dos usuários encaminhados para a rede'
q43.14	'q43.14_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 14 Registro de informações em prontuário'
q43.15	'q43.15_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 15 Elaboração de relatórios sobre casos em acompanhamento'
q43.16	'q43.16_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 16 Visitas Domiciliares'
q43.17	'q43.17_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 17 Atividades com a família do usuário'
q43.18	'q43.18_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 18 Mobilização dos usuários para acesso ao serviço'
q43.19	'q43.19_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 19 Apoio e orientação aos cuidadores familiares'
q43.20	'q43.20_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 20 Orientação sobre tecnologias assistivas'
q43.21	'q43.21_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 21 Orientação e apoio nos autocuidados'
q43.22	'q43.22_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 22 Palestras e Oficinas envolvendo a comunidade'
q43.23	'q43.23_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 23 Provimento de bens materiais'
q43.24	'q43.24_Indique as ações e atividades desenvolvidas no âmbito do Serviço de Proteção Social Especial para Pessoas Com Deficiência, Idosas e suas Famílias: - 24 Provisão de órteses e próteses'
q44.0	'q44.0_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 0 Não atendeu'
q44.1	'q44.1_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 1 Sim, atendeu Povos Indígenas'
q44.2	'q44.2_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 2 Sim, atendeu Comunidade Quilombola'
q44.3	'q44.3_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 3 Sim, atendeu Comunidade Ribeirinha'
q44.4	'q44.4_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 4 Sim, atendeu Povos Ciganos'
q44.5	'q44.5_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 5 Sim, atendeu Comunidades Extrativistas'
q44.6	'q44.6_No ano passado, este CREAS atendeu povos e comunidades tradicionais? 6 Sim, atendeu outros povos e comunidades tradicionais'
q45	'q45_Este CREAS realiza cadastramento da população em situação de rua no CadÚnico?'
q46	'q46_Este CREAS utiliza o Prontuário SUAS no modelo disponibilizado pelo MDS?'
q47.1.1	'q47.1.1_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.1.2	'q47.1.2_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 2 Recebe usuários encaminhados por este CREAS'
q47.1.3	'q47.1.3_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 3 Encaminha usuários para este CREAS'
q47.1.4	'q47.1.4_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 4 Acompanha os encaminhamentos'
q47.1.5	'q47.1.5_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 5 Realiza reuniões periódicas'
q47.1.6	'q47.1.6_Indique as ações de articulação deste CREAS:Serviços de Acolhimento (abrigos e outros) - 6 Troca Informações'
q47.1.7	'q47.1.7_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 7 Realiza estudos de caso em conjunto'
q47.1.8	'q47.1.8_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 8 Desenvolve atividades em parceria'
q47.1.0	'q47.1.0_Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 0 Não tem nenhuma articulação'
q47.1.99 	'q47.1.99 _Indique as ações de articulação deste CREAS: Serviços de Acolhimento (abrigos e outros) - 99 Serviço ou instituição não existente no Município'
q47.2.1	'q47.2.1_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.2.2	'q47.2.2_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 2 Recebe usuários encaminhados por este CREAS'
q47.2.3	'q47.2.3_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 3 Encaminha usuários para este CREAS'
q47.2.4	'q47.2.4_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 4 Acompanha os encaminhamentos'
q47.2.5	'q47.2.5_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 5 Realiza reuniões periódicas'
q47.2.6	'q47.2.6_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 6 Troca Informações'
q47.2.7	'q47.2.7_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 7 Realiza estudos de caso em conjunto'
q47.2.8	'q47.2.8_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 8 Desenvolve atividades em parceria'
q47.2.0	'q47.2.0_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 0 Não tem nenhuma articulação'
q47.2.99	'q47.2.99_Indique as ações de articulação deste CREAS: Centro de Referência Especializado para população em situação de rua (Centro POP) - 99 Serviço ou instituição não existente no Município'
q47.3.1	'q47.3.1_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.3.2	'q47.3.2_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 2 Recebe usuários encaminhados por este CREAS'
q47.3.3	'q47.3.3_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 3 Encaminha usuários para este CREAS'
q47.3.4	'q47.3.4_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 4 Acompanha os encaminhamentos'
q47.3.5	'q47.3.5_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 5 Realiza reuniões periódicas'
q47.3.6	'q47.3.6_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 6 Troca Informações'
q47.3.7	'q47.3.7_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 7 Realiza estudos de caso em conjunto'
q47.3.8	'q47.3.8_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 8 Desenvolve atividades em parceria'
q47.3.0	'q47.3.0_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 0 Não tem nenhuma articulação'
q47.3.99	'q47.3.99_Indique as ações de articulação deste CREAS: Centro de Referência de Assistência Social (CRAS) - 99 Serviço ou instituição não existente no Município'
q47.4.1	'q47.4.1_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.4.2	'q47.4.2_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 2 Recebe usuários encaminhados por este CREAS'
q47.4.3	'q47.4.3_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 3 Encaminha usuários para este CREAS'
q47.4.4	'q47.4.4_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 4 Acompanha os encaminhamentos'
q47.4.5	'q47.4.5_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 5 Realiza reuniões periódicas'
q47.4.6	'q47.4.6_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 6 Troca Informações'
q47.4.7	'q47.4.7_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 7 Realiza estudos de caso em conjunto'
q47.4.8	'q47.4.8_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 8 Desenvolve atividades em parceria'
q47.4.0	'q47.4.0_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 0 Não tem nenhuma articulação'
q47.4.99	'q47.4.99_Indique as ações de articulação deste CREAS: Programação de Erradicação do Trabalho Infantil - PETI - 99 Serviço ou instituição não existente no Município'
q47.5.1	'q47.5.1_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.5.2	'q47.5.2_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 2 Recebe usuários encaminhados por este CREAS'
q47.5.3	'q47.5.3_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 3 Encaminha usuários para este CREAS'
q47.5.4	'q47.5.4_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 4 Acompanha os encaminhamentos'
q47.5.5	'q47.5.5_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 5 Realiza reuniões periódicas'
q47.5.6	'q47.5.6_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 6 Troca Informações'
q47.5.7	'q47.5.7_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 7 Realiza estudos de caso em conjunto'
q47.5.8	'q47.5.8_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 8 Desenvolve atividades em parceria'
q47.5.0	'q47.5.0_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 0 Não tem nenhuma articulação'
q47.5.99	'q47.5.99_Indique as ações de articulação deste CREAS: Demais serviços da rede socioassistencial - 99 Serviço ou instituição não existente no Município'
q47.6.1	'q47.6.1_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.6.2	'q47.6.2_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 2 Recebe usuários encaminhados por este CREAS'
q47.6.3	'q47.6.3_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 3 Encaminha usuários para este CREAS'
q47.6.4	'q47.6.4_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 4 Acompanha os encaminhamentos'
q47.6.5	'q47.6.5_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 5 Realiza reuniões periódicas'
q47.6.6	'q47.6.6_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 6 Troca Informações'
q47.6.7	'q47.6.7_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 7 Realiza estudos de caso em conjunto'
q47.6.8	'q47.6.8_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 8 Desenvolve atividades em parceria'
q47.6.0	'q47.6.0_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 0 Não tem nenhuma articulação'
q47.6.99	'q47.6.99_Indique as ações de articulação deste CREAS: Centro DIA para pessoas com deficiência - 99 Serviço ou instituição não existente no Município'
q47.7.1	'q47.7.1_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.7.2	'q47.7.2_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 2 Recebe usuários encaminhados por este CREAS'
q47.7.3	'q47.7.3_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 3 Encaminha usuários para este CREAS'
q47.7.4	'q47.7.4_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 4 Acompanha os encaminhamentos'
q47.7.5	'q47.7.5_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 5 Realiza reuniões periódicas'
q47.7.6	'q47.7.6_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 6 Troca Informações'
q47.7.7	'q47.7.7_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 7 Realiza estudos de caso em conjunto'
q47.7.8	'q47.7.8_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 8 Desenvolve atividades em parceria'
q47.7.0	'q47.7.0_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 0 Não tem nenhuma articulação'
q47.7.99	'q47.7.99_Indique as ações de articulação deste CREAS: Serviços de Saúde Mental (CAPSi, CAPSad, ambulatórios, etc.) - 99 Serviço ou instituição não existente no Município'
q47.8.1	'q47.8.1_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.8.2	'q47.8.2_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 2 Recebe usuários encaminhados por este CREAS'
q47.8.3	'q47.8.3_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 3 Encaminha usuários para este CREAS'
q47.8.4	'q47.8.4_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 4 Acompanha os encaminhamentos'
q47.8.5	'q47.8.5_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 5 Realiza reuniões periódicas'
q47.8.6	'q47.8.6_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 6 Troca Informações'
q47.8.7	'q47.8.7_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 7 Realiza estudos de caso em conjunto'
q47.8.8	'q47.8.8_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 8 Desenvolve atividades em parceria'
q47.8.0	'q47.8.0_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 0 Não tem nenhuma articulação'
q47.8.99	'q47.8.99_Indique as ações de articulação deste CREAS: Demais Serviços da rede de Saúde - 99 Serviço ou instituição não existente no Município'
q47.9.1	'q47.9.1_Indique as ações de articulação deste CREAS: Serviços de Educação - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.9.2	'q47.9.2_Indique as ações de articulação deste CREAS: Serviços de Educação - 2 Recebe usuários encaminhados por este CREAS'
q47.9.3	'q47.9.3_Indique as ações de articulação deste CREAS: Serviços de Educação - 3 Encaminha usuários para este CREAS'
q47.9.4	'q47.9.4_Indique as ações de articulação deste CREAS: Serviços de Educação - 4 Acompanha os encaminhamentos'
q47.9.5	'q47.9.5_Indique as ações de articulação deste CREAS: Serviços de Educação - 5 Realiza reuniões periódicas'
q47.9.6	'q47.9.6_Indique as ações de articulação deste CREAS: Serviços de Educação - 6 Troca Informações'
q47.9.7	'q47.9.7_Indique as ações de articulação deste CREAS: Serviços de Educação - 7 Realiza estudos de caso em conjunto'
q47.9.8	'q47.9.8_Indique as ações de articulação deste CREAS: Serviços de Educação - 8 Desenvolve atividades em parceria'
q47.9.0	'q47.9.0_Indique as ações de articulação deste CREAS: Serviços de Educação - 0 Não tem nenhuma articulação'
q47.9.99	'q47.9.99_Indique as ações de articulação deste CREAS: Serviços de Educação - 99 Serviço ou instituição não existente no Município'
q47.10.1	'q47.10.1_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.10.2	'q47.10.2_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 2 Recebe usuários encaminhados por este CREAS'
q47.10.3	'q47.10.3_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 3 Encaminha usuários para este CREAS'
q47.10.4	'q47.10.4_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 4 Acompanha os encaminhamentos'
q47.10.5	'q47.10.5_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 5 Realiza reuniões periódicas'
q47.10.6	'q47.10.6_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 6 Troca Informações'
q47.10.7	'q47.10.7_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 7 Realiza estudos de caso em conjunto'
q47.10.8	'q47.10.8_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 8 Desenvolve atividades em parceria'
q47.10.0	'q47.10.0_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 0 Não tem nenhuma articulação'
q47.10.99	'q47.10.99_Indique as ações de articulação deste CREAS: Serviços de outras políticas públicas - 99 Serviço ou instituição não existente no Município'
q47.11.1	'q47.11.1_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.11.2	'q47.11.2_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 2 Recebe usuários encaminhados por este CREAS'
q47.11.3	'q47.11.3_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 3 Encaminha usuários para este CREAS'
q47.11.4	'q47.11.4_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 4 Acompanha os encaminhamentos'
q47.11.5	'q47.11.5_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 5 Realiza reuniões periódicas'
q47.11.6	'q47.11.6_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 6 Troca Informações'
q47.11.7	'q47.11.7_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 7 Realiza estudos de caso em conjunto'
q47.11.8	'q47.11.8_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 8 Desenvolve atividades em parceria'
q47.11.0	'q47.11.0_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 0 Não tem nenhuma articulação'
q47.11.99	'q47.11.99_Indique as ações de articulação deste CREAS: Órgãos responsáveis pela emissão de documentação civil básica - 99 Serviço ou instituição não existente no Município'
q47.12.1	'q47.12.1_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.12.2	'q47.12.2_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 2 Recebe usuários encaminhados por este CREAS'
q47.12.3	'q47.12.3_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 3 Encaminha usuários para este CREAS'
q47.12.4	'q47.12.4_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 4 Acompanha os encaminhamentos'
q47.12.5	'q47.12.5_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 5 Realiza reuniões periódicas'
q47.12.6	'q47.12.6_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 6 Troca Informações'
q47.12.7	'q47.12.7_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 7 Realiza estudos de caso em conjunto'
q47.12.8	'q47.12.8_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 8 Desenvolve atividades em parceria'
q47.12.0	'q47.12.0_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 0 Não tem nenhuma articulação'
q47.12.99	'q47.12.99_Indique as ações de articulação deste CREAS: Serviços/Programas de Segurança Alimentar - 99 Serviço ou instituição não existente no Município'
q47.13.1	'q47.13.1_Indique as ações de articulação deste CREAS: Poder Judiciário - 1 Possui dados da localização (endereço, telefone, etc.)'
q47.13.2	'q47.13.2_Indique as ações de articulação deste CREAS: Poder Judiciário - 2 Recebe usuários encaminhados por este CREAS'
q47.13.3	'q47.13.3_Indique as ações de articulação deste CREAS: Poder Judiciário - 3 Encaminha usuários para este CREAS'
q47.13.4	'q47.13.4_Indique as ações de articulação deste CREAS: Poder Judiciário - 4 Acompanha os encaminhamentos'
q47.13.5	'q47.13.5_Indique as ações de articulação deste CREAS: Poder Judiciário - 5 Realiza reuniões periódicas'
q47.13.6	'q47.13.6_Indique as ações de articulação deste CREAS: Poder Judiciário - 6 Troca Informações'
q47.13.7	'q47.13.7_Indique as ações de articulação deste CREAS: Poder Judiciário - 7 Realiza estudos de caso em conjunto'
q47.13.8	'q47.13.8_Indique as ações de articulação deste CREAS: Poder Judiciário - 8 Desenvolve atividades em parceria'
q47.13.0	'q47.13.0_Indique as ações de articulação deste CREAS: Poder Judiciário - 0 Não tem nenhuma articulação'
q47.13.99	'q47.13.99_Indique as ações de articulação deste CREAS: Poder Judiciário - 99 Serviço ou instituição não existente no Município'
q47.14.1	'q47.14.1_Indique as ações de articulação deste CREAS: Ministério Público- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.14.2	'q47.14.2_Indique as ações de articulação deste CREAS: Ministério Público- 2 Recebe usuários encaminhados por este CREAS'
q47.14.3	'q47.14.3_Indique as ações de articulação deste CREAS: Ministério Público- 3 Encaminha usuários para este CREAS'
q47.14.4	'q47.14.4_Indique as ações de articulação deste CREAS: Ministério Público- 4 Acompanha os encaminhamentos'
q47.14.5	'q47.14.5_Indique as ações de articulação deste CREAS: Ministério Público- 5 Realiza reuniões periódicas'
q47.14.6	'q47.14.6_Indique as ações de articulação deste CREAS: Ministério Público- 6 Troca Informações'
q47.14.7	'q47.14.7_Indique as ações de articulação deste CREAS: Ministério Público- 7 Realiza estudos de caso em conjunto'
q47.14.8	'q47.14.8_Indique as ações de articulação deste CREAS: Ministério Público- 8 Desenvolve atividades em parceria'
q47.14.0	'q47.14.0_Indique as ações de articulação deste CREAS: Ministério Público- 0 Não tem nenhuma articulação'
q47.14.99	'q47.14.99_Indique as ações de articulação deste CREAS: Ministério Público- 99 Serviço ou instituição não existente no Município'
q47.15.1	'q47.15.1_Indique as ações de articulação deste CREAS: Defensoria Pública- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.15.2	'q47.15.2_Indique as ações de articulação deste CREAS: Defensoria Pública- 2 Recebe usuários encaminhados por este CREAS'
q47.15.3	'q47.15.3_Indique as ações de articulação deste CREAS: Defensoria Pública- 3 Encaminha usuários para este CREAS'
q47.15.4	'q47.15.4_Indique as ações de articulação deste CREAS: Defensoria Pública- 4 Acompanha os encaminhamentos'
q47.15.5	'q47.15.5_Indique as ações de articulação deste CREAS: Defensoria Pública- 5 Realiza reuniões periódicas'
q47.15.6	'q47.15.6_Indique as ações de articulação deste CREAS: Defensoria Pública- 6 Troca Informações'
q47.15.7	'q47.15.7_Indique as ações de articulação deste CREAS: Defensoria Pública- 7 Realiza estudos de caso em conjunto'
q47.15.8	'q47.15.8_Indique as ações de articulação deste CREAS: Defensoria Pública- 8 Desenvolve atividades em parceria'
q47.15.0	'q47.15.0_Indique as ações de articulação deste CREAS: Defensoria Pública- 0 Não tem nenhuma articulação'
q47.15.99	'q47.15.99_Indique as ações de articulação deste CREAS: Defensoria Pública- 99 Serviço ou instituição não existente no Município'
q47.16.1	'q47.16.1_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.16.2	'q47.16.2_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 2 Recebe usuários encaminhados por este CREAS'
q47.16.3	'q47.16.3_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 3 Encaminha usuários para este CREAS'
q47.16.4	'q47.16.4_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 4 Acompanha os encaminhamentos'
q47.16.5	'q47.16.5_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 5 Realiza reuniões periódicas'
q47.16.6	'q47.16.6_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 6 Troca Informações'
q47.16.7	'q47.16.7_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 7 Realiza estudos de caso em conjunto'
q47.16.8	'q47.16.8_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 8 Desenvolve atividades em parceria'
q47.16.0	'q47.16.0_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 0 Não tem nenhuma articulação'
q47.16.99	'q47.16.99_Indique as ações de articulação deste CREAS: Delegacias/Delegacias Especializadas- 99 Serviço ou instituição não existente no Município'
q47.17.1	'q47.17.1_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.17.2	'q47.17.2_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 2 Recebe usuários encaminhados por este CREAS'
q47.17.3	'q47.17.3_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 3 Encaminha usuários para este CREAS'
q47.17.4	'q47.17.4_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 4 Acompanha os encaminhamentos'
q47.17.5	'q47.17.5_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 5 Realiza reuniões periódicas'
q47.17.6	'q47.17.6_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 6 Troca Informações'
q47.17.7	'q47.17.7_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 7 Realiza estudos de caso em conjunto'
q47.17.8	'q47.17.8_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 8 Desenvolve atividades em parceria'
q47.17.0	'q47.17.0_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 0 Não tem nenhuma articulação'
q47.17.99	'q47.17.99_Indique as ações de articulação deste CREAS: ONG que atuam com defesa de direitos ou que realizam projetos sociais- 99 Serviço ou instituição não existente no Município'
q47.18.1	'q47.18.1_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.18.2	'q47.18.2_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 2 Recebe usuários encaminhados por este CREAS'
q47.18.3	'q47.18.3_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 3 Encaminha usuários para este CREAS'
q47.18.4	'q47.18.4_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 4 Acompanha os encaminhamentos'
q47.18.5	'q47.18.5_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 5 Realiza reuniões periódicas'
q47.18.6	'q47.18.6_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 6 Troca Informações'
q47.18.7	'q47.18.7_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 7 Realiza estudos de caso em conjunto'
q47.18.8	'q47.18.8_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 8 Desenvolve atividades em parceria'
q47.18.0	'q47.18.0_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 0 Não tem nenhuma articulação'
q47.18.99	'q47.18.99_Indique as ações de articulação deste CREAS: Instituições de Ensino e Pesquisa- 99 Serviço ou instituição não existente no Município'
q47.19.1	'q47.19.1_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.19.2	'q47.19.2_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 2 Recebe usuários encaminhados por este CREAS'
q47.19.3	'q47.19.3_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 3 Encaminha usuários para este CREAS'
q47.19.4	'q47.19.4_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 4 Acompanha os encaminhamentos'
q47.19.5	'q47.19.5_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 5 Realiza reuniões periódicas'
q47.19.6	'q47.19.6_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 6 Troca Informações'
q47.19.7	'q47.19.7_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 7 Realiza estudos de caso em conjunto'
q47.19.8	'q47.19.8_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 8 Desenvolve atividades em parceria'
q47.19.0	'q47.19.0_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 0 Não tem nenhuma articulação'
q47.19.99	'q47.19.99_Indique as ações de articulação deste CREAS: Unidades/ Serviços de outros municípios- 99 Serviço ou instituição não existente no Município'
q47.20.1	'q47.20.1_Indique as ações de articulação deste CREAS: Conselho Tutelar- 1 Possui dados da localização (endereço, telefone, etc.)'
q47.20.2	'q47.20.2_Indique as ações de articulação deste CREAS: Conselho Tutelar- 2 Recebe usuários encaminhados por este CREAS'
q47.20.3	'q47.20.3_Indique as ações de articulação deste CREAS: Conselho Tutelar- 3 Encaminha usuários para este CREAS'
q47.20.4	'q47.20.4_Indique as ações de articulação deste CREAS: Conselho Tutelar- 4 Acompanha os encaminhamentos'
q47.20.5	'q47.20.5_Indique as ações de articulação deste CREAS: Conselho Tutelar- 5 Realiza reuniões periódicas'
q47.20.6	'q47.20.6_Indique as ações de articulação deste CREAS: Conselho Tutelar- 6 Troca Informações'
q47.20.7	'q47.20.7_Indique as ações de articulação deste CREAS: Conselho Tutelar- 7 Realiza estudos de caso em conjunto'
q47.20.8	'q47.20.8_Indique as ações de articulação deste CREAS: Conselho Tutelar- 8 Desenvolve atividades em parceria'
q47.20.0	'q47.20.0_Indique as ações de articulação deste CREAS: Conselho Tutelar- 0 Não tem nenhuma articulação'
q47.20.99	'q47.20.99_Indique as ações de articulação deste CREAS: Conselho Tutelar- 99 Serviço ou instituição não existente no Município'
q48	'q48_O coordenador deste CREAS:'
q50.1	'q50.1_Responsável – Nome:'
q50.2	'q50.2_Responsável – CPF:'
q50.3	'q50.3_Responsável – Data:'
q50.4	'q50.4_Responsável – Cargo/Função:'
q50.4.1	'q50.4.1_Especifique:'
q50.5	'q50.5_Responsável – Telefone:'
q50.6	'q50.6_Responsável – E-mail:'
q51.1	'q51.1_Responsável Órgão Gestor – Nome:'
q51.2	'q51.2_Responsável Órgão Gestor – CPF:'
q51.3	'q51.3_Responsável Órgão Gestor – Data:'
q51.4	'q51.4_Responsável Órgão Gestor – Cargo/Função:'
q51.4.1	'q51.4.1_Especifique:'
q51.5	'q51.5_Responsável Órgão Gestor – Telefone:'
q51.6	'q51.6_Responsável Órgão Gestor – E-mail:'
.

*** RENAME LABELS CREAS RH - 2016

VARIABLE LABELS
q49.1	'q49.1Nome'
q49.2	'q49.2Data de Nascimento'
q49.3	'q49.3Sexo'
q49.4	'q49.4Número do CPF'
q49.5.1	'q49.5.1RG - Número'
q49.5.2	'q49.5.2RG - Órgão Emissor'
q49.5.3	'q49.5.3RG - UF'
q49.6	'q49.6Email:'
q49.7	'q49.7Escolaridade'
q49.8	'q49.8Profissão'
q49.9	'q49.9Vínculo'
q49.10	'q49.10Função'
q49.11	'q49.11Carga horária SEMANAL'
q49.12	'q49.12Início do exercício da função'
q49.13.1	'q49.13.1Principal serviço/atividade'
q49.13.2	'q49.13.2Segundo principal serviço/atividade'
q49.13.3	'q49.13.3Terceiro principal serviço/atividade'
.
